kuma/wiki/urls.py
from django.conf.urls import include, patterns, url
from django.views.generic import TemplateView

from kuma.attachments.feeds import AttachmentsFeed
from .feeds import (DocumentsRecentFeed, DocumentsReviewFeed, RevisionsFeed,
                    DocumentsUpdatedTranslationParentFeed,)


# These patterns inherit (?P<document_path>[^\$]+).
document_patterns = patterns('kuma.wiki.views',
    url(r'^$', 'document', name='wiki.document'),
    url(r'^\$revision/(?P<revision_id>\d+)$', 'revision',
        name='wiki.revision'),
    url(r'^\$history$', 'document_revisions', name='wiki.document_revisions'),
    url(r'^\$edit$', 'edit_document', name='wiki.edit_document'),
    url(r'^\$edit/(?P<revision_id>\d+)$', 'edit_document',
        name='wiki.new_revision_based_on'),
    url(r'^\$compare$', 'compare_revisions', name='wiki.compare_revisions'),
    url(r'^\$children$', 'get_children', name='wiki.get_children'),
    url(r'^\$flag', 'flag', name='wiki.flag_document'),
    url(r'^\$translate$', 'translate', name='wiki.translate'),
    url(r'^\$locales$', 'select_locale', name='wiki.select_locale'),
    url(r'^\$json$', 'json_view', name='wiki.json_slug'),
    url(r'^\$styles$', 'styles_view', name='wiki.styles'),
    url(r'^\$toc$', 'toc_view', name='wiki.toc'),
    url(r'^\$move$', 'move', name='wiki.move'),
    url(r'^\$quick-review$', 'quick_review', name='wiki.quick_review'),
    url(r'^\$samples/(?P<sample_id>.+)$', 'code_sample', name='wiki.code_sample'),
    url(r'^\$revert/(?P<revision_id>\d+)$', 'revert_document',
        name='wiki.revert_document'),
    url(r'^\$repair_breadcrumbs$',
        'repair_breadcrumbs',
        name='wiki.repair_breadcrumbs'),
    url(r'^\$delete$',
        'delete_document',
        name='wiki.delete_document'),
    url(r'^\$restore$',
        'restore_document',
        name='wiki.restore_document'),
    url(r'^\$purge$',
        'purge_document',
        name='wiki.purge_document'),

    # Un/Subscribe to document edit notifications.
    url(r'^\$subscribe$', 'subscribe_document', name='wiki.subscribe_document'),

    # Vote helpful/not helpful
    url(r'^\$vote', 'helpful_vote', name="wiki.document_vote"),
)

urlpatterns = patterns('kuma.wiki.views',
    # Un/Subscribe to locale 'ready for review' notifications.
    url(r'^/ckeditor_config.js$', 'ckeditor_config',
        name='wiki.ckeditor_config'),

    # internals
    url(r'^.json$', 'json_view', name='wiki.json'),
    url(r'^/preview-wiki-content$', 'preview_revision', name='wiki.preview'),
    url(r'^/move-requested$',
        TemplateView.as_view(template_name='wiki/move_requested.html'),
        name='wiki.move_requested'),
    url(r'^/get-documents$', 'autosuggest_documents', name='wiki.autosuggest_documents'),
    url(r'^/load/$', 'load_documents', name='wiki.load_documents'),

    # Special pages
    url(r'^/templates$', 'list_templates', name='wiki.list_templates'),
    url(r'^/tags$', 'list_tags', name='wiki.list_tags'),
    url(r'^/tag/(?P<tag>.+)$', 'list_documents', name='wiki.tag'),
    url(r'^/new$', 'new_document', name='wiki.new_document'),
    url(r'^/all$', 'list_documents', name='wiki.all_documents'),
    url(r'^/with-errors$', 'list_documents_with_errors', name='wiki.errors'),
    url(r'^/without-parent$', 'list_documents_without_parent',
        name='wiki.without_parent'),
    url(r'^/top-level$', 'list_top_level_documents',
        name='wiki.top_level'),
    url(r'^/needs-review/(?P<tag>[^/]+)$', 'list_documents_for_review',
        name='wiki.list_review_tag'),
    url(r'^/needs-review/?', 'list_documents_for_review',
        name='wiki.list_review'),
    url(r'^/localization-tag/(?P<tag>[^/]+)$', 'list_documents_with_localization_tag',
        name='wiki.list_with_localization_tag'),
    url(r'^/localization-tag/?', 'list_documents_with_localization_tag',
        name='wiki.list_with_localization_tags'),
    url(r'^/category/(?P<category>\d+)$', 'list_documents',
    name='wiki.category'),

    # Feeds
    url(r'^/feeds/(?P<format>[^/]+)/all/?',
        DocumentsRecentFeed(), name="wiki.feeds.recent_documents"),
    url(r'^/feeds/(?P<format>[^/]+)/l10n-updates/?',
        DocumentsUpdatedTranslationParentFeed(), name="wiki.feeds.l10n_updates"),
    url(r'^/feeds/(?P<format>[^/]+)/tag/(?P<tag>[^/]+)',
        DocumentsRecentFeed(), name="wiki.feeds.recent_documents"),
    url(r'^/feeds/(?P<format>[^/]+)/category/(?P<category>[^/]+)',
        DocumentsRecentFeed(), name="wiki.feeds.recent_documents_category"),
    url(r'^/feeds/(?P<format>[^/]+)/needs-review/(?P<tag>[^/]+)',
        DocumentsReviewFeed(), name="wiki.feeds.list_review_tag"),
    url(r'^/feeds/(?P<format>[^/]+)/needs-review/?',
        DocumentsReviewFeed(), name="wiki.feeds.list_review"),
    url(r'^/feeds/(?P<format>[^/]+)/revisions/?',
        RevisionsFeed(), name="wiki.feeds.recent_revisions"),
    url(r'^/feeds/(?P<format>[^/]+)/files/?',
        AttachmentsFeed(), name="attachments.feeds.recent_files"),

    (r'^/(?P<document_path>[^\$]+)', include(document_patterns)),
)

urls.py
from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.shortcuts import redirect
from django.views.i18n import javascript_catalog
from django.views.decorators.cache import cache_page

from kuma.core import views as core_views
import badger


admin.autodiscover()
badger.autodiscover()

handler403 = core_views.handler403
handler404 = core_views.handler404
handler500 = core_views.handler500

urlpatterns = patterns('',
    ('', include('kuma.landing.urls')),
    (r'^demos/', include('kuma.demos.urls')),
    (r'^events/?', include('kuma.events.urls')),
    (r'^demos', lambda x: redirect('demos')),

    # Django admin:
    (r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/wiki/document/purge/',
        'kuma.wiki.admin.purge_view',
        name='wiki.admin_bulk_purge'),
    (r'^admin/', include('smuggler.urls')),
    (r'^admin/', include(admin.site.urls)),

    (r'^search', include('kuma.search.urls')),

    # Special-case here because this used to live in the wiki app and
    # needs to keep its historical URL.
    url(r'^docs/files$',
        'kuma.attachments.views.list_files',
        name='attachments.list_files'),
    (r'^docs', include('kuma.wiki.urls')),

    # Javascript translations.
    url(r'^jsi18n/.*$', cache_page(60 * 60 * 24 * 365)(javascript_catalog),
        {'domain': 'javascript', 'packages': [settings.ROOT_PACKAGE]},
        name='jsi18n'),

    url(r'^files/', include('kuma.attachments.urls')),
    url(r'^', include('kuma.dashboards.urls')),

    # Flagged content.
    url(r'^flagged/$',
        'kuma.contentflagging.views.flagged',
        name='contentflagging.flagged'),

    # Users
    ('', include('kuma.users.urls')),

    # Badges
    (r'^badges/', include('badger.urls_simple')),

    # Services and sundry.
    (r'^', include('tidings.urls')),
    (r'^humans.txt$', 'django.views.static.serve',
        {'document_root': settings.HUMANSTXT_ROOT, 'path': 'humans.txt'}),

    url(r'^miel$', handler500, name='users.honeypot'),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

if settings.SERVE_MEDIA:
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    urlpatterns += patterns('',
        (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
          {'document_root': settings.MEDIA_ROOT}),
    )

# Legacy MindTouch redirects. These go last so that they don't mess
# with local instances' ability to serve media.
urlpatterns += patterns('',
                        url(r'^@api/deki/files/(?P<file_id>\d+)/=(?P<filename>.+)$',
                            'kuma.attachments.views.mindtouch_file_redirect',
                            name='attachments.mindtouch_file_redirect'),
                        (r'^(?P<path>.*)$', 'kuma.wiki.views.mindtouch_to_kuma_redirect'),
)

kuma/wiki/models.py
import hashlib
import json
import sys
import traceback
from datetime import datetime, timedelta
from urlparse import urlparse

try:
    from functools import wraps
except ImportError:
    from django.utils.functional import wraps

import newrelic.agent
from pyquery import PyQuery
from tower import ugettext_lazy as _lazy, ugettext as _

from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.urlresolvers import resolve
from django.db import models
from django.db.models import Count, signals
from django.dispatch import receiver
from django.http import Http404
from django.utils.decorators import available_attrs
from django.utils.functional import cached_property

import constance.config
import waffle
from south.modelsinspector import add_introspection_rules
from taggit.managers import TaggableManager
from taggit.models import ItemBase, TagBase
from taggit.utils import edit_string_for_tags, parse_tags
from teamwork.models import Team
from tidings.models import NotificationsMixin

from kuma.attachments.models import Attachment, DocumentAttachment
from kuma.core.exceptions import ProgrammingError
from kuma.core.cache import memcache
from kuma.core.fields import LocaleField
from kuma.core.urlresolvers import reverse, split_path
from kuma.search.decorators import register_live_index

from . import kumascript
from .constants import (DEKI_FILE_URL, DOCUMENT_LAST_MODIFIED_CACHE_KEY_TMPL,
                        KUMA_FILE_URL, REDIRECT_CONTENT, REDIRECT_HTML,
                        TEMPLATE_TITLE_PREFIX)
from .content import parse as parse_content
from .content import (extract_code_sample, extract_css_classnames,
                      extract_html_attributes, extract_kumascript_macro_names,
                      get_content_sections, get_seo_description, H2TOCFilter,
                      H3TOCFilter, SectionTOCFilter)
from .jobs import DocumentZoneStackJob, DocumentZoneURLRemapsJob
from .exceptions import (DocumentRenderedContentNotAvailable,
                         DocumentRenderingInProgress, PageMoveError,
                         SlugCollision, UniqueCollision)
from .managers import (DeletedDocumentManager, DocumentAdminManager,
                       DocumentManager, RevisionIPManager,
                       TaggedDocumentManager, TransformManager)
from .search import WikiDocumentType
from .signals import render_done


add_introspection_rules([], ["^utils\.OverwritingFileField"])


def cache_with_field(field_name):
    """Decorator for generated content methods.

    If the backing model field is null, or kwarg force_fresh is True, call the
    decorated method to generate and return the content.

    Otherwise, just return the value in the backing model field.
    """
    def decorator(fn):
        @wraps(fn, assigned=available_attrs(fn))
        def wrapper(self, *args, **kwargs):
            force_fresh = kwargs.pop('force_fresh', False)

            # Try getting the value using the DB field.
            field_val = getattr(self, field_name)
            if field_val is not None and not force_fresh:
                return field_val

            # DB field is blank, or we're forced to generate it fresh.
            field_val = fn(self, force_fresh=force_fresh)
            setattr(self, field_name, field_val)
            return field_val

        return wrapper
    return decorator


def _inherited(parent_attr, direct_attr):
    """Return a descriptor delegating to an attr of the original document.

    If `self` is a translation, the descriptor delegates to the attribute
    `parent_attr` from the original document. Otherwise, it delegates to the
    attribute `direct_attr` from `self`.

    Use this only on a reference to another object, like a ManyToMany or a
    ForeignKey. Using it on a normal field won't work well, as it'll preclude
    the use of that field in QuerySet field lookups. Also, ModelForms that are
    passed instance=this_obj won't see the inherited value.

    """
    getter = lambda self: (getattr(self.parent, parent_attr)
                           if self.parent and self.parent.id != self.id
                           else getattr(self, direct_attr))
    setter = lambda self, val: (setattr(self.parent, parent_attr, val)
                                if self.parent and self.parent.id != self.id
                                else setattr(self, direct_attr, val))
    return property(getter, setter)


def valid_slug_parent(slug, locale):
    slug_bits = slug.split('/')
    slug_bits.pop()
    parent = None
    if slug_bits:
        parent_slug = '/'.join(slug_bits)
        try:
            parent = Document.objects.get(locale=locale, slug=parent_slug)
        except Document.DoesNotExist:
            raise Exception(_("Parent %s/%s does not exist." % (locale,
                                                         parent_slug)))

    return parent


class DocumentTag(TagBase):
    """A tag indexing a document"""
    class Meta:
        verbose_name = _("Document Tag")
        verbose_name_plural = _("Document Tags")


class TaggedDocument(ItemBase):
    """Through model, for tags on Documents"""
    content_object = models.ForeignKey('Document')
    tag = models.ForeignKey(DocumentTag)

    objects = TaggedDocumentManager()

    # FIXME: This is copypasta from taggit/models.py#TaggedItemBase, which I
    # don't like. But, it seems to be the only way to get *both* a custom tag
    # *and* a custom through model.
    # See: https://github.com/boar/boar/blob/master/boar/articles/models.py#L63
    @classmethod
    def tags_for(cls, model, instance=None):
        if instance is not None:
            return DocumentTag.objects.filter(
                taggeddocument__content_object=instance)
        return DocumentTag.objects.filter(
            taggeddocument__content_object__isnull=False).distinct()


@register_live_index
class Document(NotificationsMixin, models.Model):
    """A localized knowledgebase document, not revision-specific."""
    CATEGORIES = (
        (00, _lazy(u'Uncategorized')),
        (10, _lazy(u'Reference')),
    )
    TOC_FILTERS = {
        1: SectionTOCFilter,
        2: H2TOCFilter,
        3: H3TOCFilter,
        4: SectionTOCFilter
    }

    title = models.CharField(max_length=255, db_index=True)
    slug = models.CharField(max_length=255, db_index=True)

    # NOTE: Documents are indexed by tags, but tags are edited in Revisions.
    # Also, using a custom through table to isolate Document tags from those
    # used in other models and apps. (Works better than namespaces, for
    # completion and such.)
    tags = TaggableManager(through=TaggedDocument)

    # Is this document a template or not?
    is_template = models.BooleanField(default=False, editable=False,
                                      db_index=True)

    # Is this a redirect or not?
    is_redirect = models.BooleanField(default=False, editable=False,
                                      db_index=True)

    # Is this document localizable or not?
    is_localizable = models.BooleanField(default=True, db_index=True)

    locale = LocaleField(default=settings.WIKI_DEFAULT_LANGUAGE, db_index=True)

    # Latest approved revision. L10n dashboard depends on this being so (rather
    # than being able to set it to earlier approved revisions). (Remove "+" to
    # enable reverse link.)
    current_revision = models.ForeignKey('Revision', null=True,
                                         related_name='current_for+')

    # The Document I was translated from. NULL if this doc is in the default
    # locale or it is nonlocalizable. TODO: validate against
    # settings.WIKI_DEFAULT_LANGUAGE.
    parent = models.ForeignKey('self', related_name='translations',
                               null=True, blank=True)

    parent_topic = models.ForeignKey('self', related_name='children',
                                     null=True, blank=True)

    files = models.ManyToManyField(Attachment,
                                   through=DocumentAttachment)

    # JSON representation of Document for API results, built on save
    json = models.TextField(editable=False, blank=True, null=True)

    # Raw HTML of approved revision's wiki markup
    html = models.TextField(editable=False)

    # Cached result of kumascript and other offline processors (if any)
    rendered_html = models.TextField(editable=False, blank=True, null=True)

    # Errors (if any) from the last rendering run
    rendered_errors = models.TextField(editable=False, blank=True, null=True)

    # Whether or not to automatically defer rendering of this page to a queued
    # offline task. Generally used for complex pages that need time
    defer_rendering = models.BooleanField(default=False, db_index=True)

    # Timestamp when this document was last scheduled for a render
    render_scheduled_at = models.DateTimeField(null=True, db_index=True)

    # Timestamp when a render for this document was last started
    render_started_at = models.DateTimeField(null=True, db_index=True)

    # Timestamp when this document was last rendered
    last_rendered_at = models.DateTimeField(null=True, db_index=True)

    # Maximum age (in seconds) before this document needs re-rendering
    render_max_age = models.IntegerField(blank=True, null=True)

    # Time after which this document needs re-rendering
    render_expires = models.DateTimeField(blank=True, null=True, db_index=True)

    # A document's category much always be that of its parent. If it has no
    # parent, it can do what it wants. This invariant is enforced in save().
    category = models.IntegerField(choices=CATEGORIES, db_index=True)

    # Team to which this document belongs, if any
    team = models.ForeignKey(Team, blank=True, null=True)

    # Whether this page is deleted.
    deleted = models.BooleanField(default=False, db_index=True)

kuma/wiki/templates/wiki/includes/ace_scripts.html
<script type="text/javascript" src="/media/js/libs/ace/ace.js"></script>
<script type="text/javascript" src="/media/js/libs/ace/mode-javascript.js"></script>
<script type="text/javascript" src="/media/js/libs/ace/theme-dreamweaver.js"></script>
<script type="text/javascript" src="/media/js/libs/ace/worker-javascript.js"></script>

kuma/wiki/templates/wiki/includes/ckeditor_scripts.html
<!-- Production ready CKEditor scripts -->
<script src="{{ MEDIA_URL }}js/libs/ckeditor/build/ckeditor/ckeditor.js?build={{ BUILD_ID_JS }}"></script>
<script src="{{ MEDIA_URL }}js/libs/ckeditor/build/ckeditor/adapters/jquery.js?build={{ BUILD_ID_JS }}"></script>

{#
<!-- Development version -->
<script src="{{ MEDIA_URL }}js/libs/ckeditor/source/ckeditor/ckeditor.js?build={{ BUILD_ID_JS }}"></script>
<script src="{{ MEDIA_URL }}js/libs/ckeditor/source/ckeditor/adapters/jquery.js?build={{ BUILD_ID_JS }}"></script>
#}
<script>
  // Define the path to non-core plugins.
  (
    'scayt,wsc,mdn-attachment,mdn-format,mdn-sticky-toolbar,mdn-image-attachment,mdn-link-customization,' +
    'mdn-link-launch,mdn-redirect,mdn-sample-finder,mdn-sampler,mdn-spell,mdn-syntaxhighlighter,' +
    'mdn-system-integration,mdn-table-customization,mdn-toggle-block,mdn-wrapstyle,descriptionlist,' +
    'tablesort,texzilla,youtube'
  ).split(',').forEach(function(pluginName) {
    CKEDITOR.plugins.addExternal(pluginName, '{{ MEDIA_URL }}js/libs/ckeditor/source/plugins/' + pluginName + '/');
  });
</script>

kuma/wiki/templates/wiki/includes/document_toc_field.html
<li class="clear">
  <label for="id_toc_depth"><dfn title="{{_('Generate table of contents')}}">{{_('TOC:')}}</dfn></label>
  {{ revision_form.toc_depth }}
</li>

kuma/wiki/templates/wiki/includes/guide_links.html
<div class="guide-links">
  <a target="_blank" href="{{ wiki_url('MDN/Community') }}">Need Help?</a>
  &bull;
  <a target="_blank" href="{{ wiki_url('MDN/Contribute/Editor') }}">Editor Guide</a>
  &bull;
  <a target="_blank" href="{{ wiki_url('MDN/Contribute/Content/Style_guide') }}">Style Guide</a>
</div>

kuma/wiki/templates/wiki/includes/kumascript_errors.html
<div class="warning" id="kserrors">
<p>
{{ ngettext(
  'There was a scripting error on this page. While it is being addressed by site editors, you can view partial content below.',
  'There were scripting errors on this page. While those are being addressed by site editors, you can view partial content below.',
  kumascript_errors|count)
}}

</p>
{% if request.user.is_authenticated() %}
  <button type="button" class="kserrors-details-toggle" data-alternate-message="{{ _('Hide error information') }}">
    {{ ngettext(
      'More information about this error',
      'More information about these errors',
      kumascript_errors|count)
    }}
  </button>
  <div class="kserrors-details hidden">
      <p>{% trans %}
        Anyone with an MDN profile can edit a document to fix an error. Use the <a href="/docs/MDN/Kuma/Troubleshooting_KumaScript_errors">KumaScript troubleshooting guide</a> as a starting point.
      {% endtrans %}</p>

      <ul>
      {% for error in kumascript_errors %}
        <li>
            {% if error.args %}
                {% set error_type = error.args[0] %}
                {{ _('Error type:') }} <strong class="type">{{ error_type }}</strong><br>

                {% set error_meta = error.args[2] %}
                {% if error_meta %}
                    {% set template_name = error_meta.name %}

                    {% if '$' not in template_name %}
                        {% set template_slug = 'Template:{name}' | f(name=template_name) %}
                        {% set edit_url = url('wiki.edit_document', template_slug) %}
                        {% set new_url = url('wiki.new_document') + '?slug=Template:{name}' | f(name=template_name) %}
                    {% endif %}

                    {{ _('In macro:') }} <code>{{ template_name }}</code>

                    {% if 'status 404' in error.message %}
                        {% if new_url %}
                            (<a href="{{ new_url }}">{{ _('Create Template') }}</a>)
                        {% endif %}
                    {% elif edit_url  %}
                        (<a href="{{ edit_url }}">{{ _('Edit Template') }}</a>)
                    {% endif %}<br>

                    {{ _('Parsing macro:') }} <code>{{ template_name }}({% if error_meta.token %}{{ error_meta.token.args }}{% endif %})</code> {% if document %}(<a href="{{ url('wiki.edit_document', document.slug) }}">{{ _('Edit Document') }}</a>){% endif %}
                {% endif %}
            {% endif %}

            {{ _('Full text of error:') }}<br>
            <pre class="message brush: text">{{ error.message }}</pre>
        </li>
      {% endfor %}
      </ul>
  </div>
{% endif %}
</div>

kuma/wiki/templates/wiki/includes/more_help.html
{% from 'includes/common_macros.html' import search_box %}
  <div id="more-help">
    <div class="wrap">
      <h2>{{ _("Couldn't find what you were looking for?") }}</h2>
      <ul>
        <li>
          {{ _('Browse other articles about <a href="{url}">{category}</a>')|fe(url=url('wiki.category', document.category), category=document.get_category_display()) }}
        </li>
        <li>
          <a href="{{ url('wiki.document', 'ask') }}">{{ _('Ask our awesome support community for help') }}</a>
        </li>
      </ul>
      {{ search_box(settings, id=False, prefix=_('Or try searching:')) }}
    </div>
  </div>

kuma/wiki/templates/wiki/includes/page_buttons.html
{% macro page_buttons(wiki, document, discard_href, location) %}

{% if not discard_href %}
  {% if document %}
    {% set discard_href = url('wiki.document', document.full_path) %}
  {% else %}
    {% set discard_href = url('wiki.new_document') %}
  {% endif %}
{% endif %}


{% if location == 'top' %}
  {% if document %}<iframe id="save-and-edit-target" name="save-and-edit-target"></iframe>{% endif %}
  <input type="hidden" id="new-page-href" value="{{ url('wiki.new_document') }}">
  <input type="hidden" id="new-page-label" value="{{ _('New Page') }}">
  <input type="hidden" id="new-page-msg" value="{{ _('Discard changes and create a new document?') }}">
{% endif %}

<ul class="page-buttons">
  {% if document %}
  <li>
    <button type="submit" class="button positive btn-save-and-edit" data-optimizely-hook="button-save-and-keep-editing button-save-and-keep-editing-{{ location }}"><span>{{ _('Save and Keep Editing') }}</span><i aria-hidden="true" class="icon-edit"></i></button>
  </li>
  {% endif %}
  <li>
    <button type="submit" class="button positive btn-save">{{ _('Save Changes') }}<i aria-hidden="true" class="icon-save"></i></button>
  </li>
  {% if (not document and not is_template) or (document and not document.is_template) %}
  <li>
    <button type="button" class="btn-preview" data-preview-url="{{ url('wiki.preview') }}">{{ _('Preview Changes') }}<i aria-hidden="true" class="icon-play-circle"></i></button>
  </li>
  {% endif %}
  <li>
    <a href="{{ discard_href }}" class="button negative btn-discard">{{ _('Discard Changes') }}<i aria-hidden="true" class="icon-undo"></i></a>
  </li>
</ul>

{% endmacro %}

kuma/wiki/templates/wiki/includes/review_tags.html
<div class="wiki-block">

    <h3>{{_('Review needed?')}}</h3>
    {{ revision_form.review_tags|safe }}

</div>

kuma/wiki/templates/wiki/includes/revision_comment.html
<section class="wiki-block" id="page-comment">
  <h3><i aria-hidden="true" class="icon-comment"></i>{{_('Revision Comment')}} <a href="{{ wiki_url('Project:MDN/Contributing/Editor_guide/Editing#The_revision_comment_box') }}"><i aria-hidden="true" title="{{ _('Learn how to use Revision Comments') }}" class="icon-question-sign editor-help-icon"></i></a></h3>
  <p>{{_('Tell us why you made additions and changes. It is optional, but will make page history easier to understand.')}}</p>
  {{ revision_form.comment | safe }}
</section>

kuma/wiki/templates/wiki/includes/revision_diff_table.html
{% if revision_from.id != revision_to.id %}
	{% set from_content = revision_from.content %}
{% else %}
	{% set from_content = '' %}
{% endif %}
{{ diff_table(from_content, revision_to.content, revision_from.id, revision_to.id) }}

kuma/wiki/templates/wiki/includes/tag_suggestions.html
{% set suggestions = WIKI_DOCUMENT_TAG_SUGGESTIONS or '[]' %}
<script type="text/javascript">
  mdn.wiki.tagSuggestions = {{ suggestions|safe }};
</script>